version: "3"
services:
  basic-instance:
    build: .
    env_file:
      - ./.env
    command: [ "cargo", "run", "--", "--instance=basic" ]
  test-check-poi-basic:
    build: .
    env_file:
      - ./.env
    command: [ "cargo", "run", "--", "--check=poi_ok" ]
